### PR TITLE
Avoid interfering of internal make variables

### LINKED ISSUE #648: Wrong Compiler Selected When Building With Make
This line
https://github.com/fortran-lang/stdlib/blob/9f1aa24016b652d25cd0493ac9c0111eb3de197b/Makefile.manual#L3
should set `FC` to gfortran, if no other compiler is defined. But on some (don't know on how many) systems `FC` is preset to `f77`. Since I don't have `f77` (and I doubt it would be able to compile stdlib) the build process fails.
Is there anything we can do about this issue? Maybe check the value of `FC` if it is set to such a default value and print a error/warning message?
The current warning is a little bit misleading:
`f77: No such file or directory`

Testet on:
Arch Linux, GNU Make 4.3 built for x86_64-pc-linux-gnu
Fedora 35, GNU Make 4.3 built for x86_64-redhat-linux-gnu

### PR DESCRIPTION
**Pull request by awvwgk**
Closes #648

### CODE REVIEW

**Comment by Carltoffel** [comment]
I don't know what happens here, but this is what I get:
```
fortran-stdlib$ make -f Makefile.manual                                                                                                                                        
make -f Makefile.manual --directory=src
make[1]: Entering directory '/home/burkert1/programs/fortran-stdlib/src'
Wall -Wextra -Wimplicit-interface -fPIC -g -fcheck=all -fno-range-check -c stdlib_kinds.f90
make[1]: Wall: No such file or directory
make[1]: [Makefile.manual:89: stdlib_kinds.o] Error 127 (ignored)
Wall -Wextra -Wimplicit-interface -fPIC -g -fcheck=all -fno-range-check -c stdlib_optval.f90
make[1]: Wall: No such file or directory
...
```
Looks like the `?=` operator is somehow broken on my system.

**Comment by awvwgk** [comment]
Recursive make was never really my strength, dunno I would have to check the manual to figure out how you can avoid the make defaults and still pass optional values down the recursive invocations.

**Comment by Carltoffel** [comment]
> Somehow the - in front of the -Wall compiler option got stripped.

It's not the compiler which cannot find the file "Wall", but `make` tries to execute `Wall` as command. `FC` is empty, therefore `Wall` is the first "command" `$(FC) $(FFLAGS)...`.
TBH this doesn't look like a `fpm` issue. This surely is a make issue. If I do `@echo ">$(FC)<"` in the `all` target, it prints `><`. If I change `?=` to `=` to set `FC` it works! Somehow `FC` is not set but cannot be overwritten. For `FFLAGS` the `?=` works as expected...

**Comment by Romendakil** [comment]
> It's not the compiler which cannot find the file "Wall", but `make` tries to execute `Wall` as command. `FC` is empty, therefore `Wall` is the first "command" `$(FC) $(FFLAGS)...`. TBH this doesn't look like a `fpm` issue. This surely is a make issue. If I do `@echo ">$(FC)<"` in the `all` target, it prints `><`. If I change `?=` to `=` to set `FC` it works! Somehow `FC` is not set but cannot be overwritten. For `FFLAGS` the `?=` works as expected...

Oops, sorry, you are right. My remark was too hasty. It seems strange. ?= is a GNU extension, it is not POSIX. It might not even work on macOS.

**Comment by awvwgk** [comment]
Well, I guess that won't work than.

**Pull request closed without merging**
