### PR TITLE
Changes directory structure of stdlib as discussed in #216

### PR DESCRIPTION
**Pull request by jvdp1**
This PR changes the directory structure of stdlib as discussed in #216 opened by @wclodius2

In short:
* all "experimental" terms have been removed from the names of the modules
* a version ("experimental") tag has been added to all procedures and also in the specs. FORD uses the version tag as meta-data.

### CODE REVIEW

**Comment by jvdp1** [comment]
The FORD documentation can be dowloaded [here[(https://github.com/fortran-lang/stdlib/suites/951359601/artifacts/11866410).

**Comment by jvdp1** [comment]
This is a major change in terms of structure for `stdlib`. 
Is everybody ok with that? It should be easier for the users to use `stdlib` now. However, is it still clear enough that the procedures are `experimentatl`?

**Comment by certik** [comment]
I think we are ok with the general idea to do it like this.

I think the only thing to figure out is how exactly to document that all those routines are experimental. Should we also add a comment next to each subroutine in the source file? I think I would prefer that --- we want to convey as clearly as possible that the subroutine is experimental.

**Comment by leonfoks** [comment]
@certik I believe having the version: experimental as @jvdp1 has done should suffice.  Having the experimental tag in the Ford  doc comments covers all bases.  Is there anywhere else that would more clearly indicate the experimental nature of a function?

Could we have a script that simply parses out "version: experimental" and lists them in the docs?  Maybe this is something we could add to FORD?

**Comment by certik** [comment]
Given how important the change is, I am CCing others who committed the most code so far: @zbeekman, @nshaffer, @scivision, @fiolj, @MarDiehl, @aradi, @ivan-pi, to make sure everybody is on board.

**Comment by fiolj** [comment]
I've been away for a while. I am ok with the change in structure.

**Comment by jvdp1** [comment]
> Could we have a script that simply parses out "version: experimental" and lists them in the docs? Maybe this is something we could add to FORD?

The version of each procedure is mentioned in FORD website when you open the page of a procedure.
I think it would be also nice if the version would be added in the table that lists all the procedures.

**Comment by nshaffer** [comment]
So in the generated docs, experimental interfaces get a subsection like

## Version
Experimental

What would this say for stable interfaces, "stable"? Seems strange to me. Might just be the word "version". If we are only classifying interfaces as "experimental" or "stable", I think maybe calling this section "status" makes more sense? If I'm a user and I see "Version: stable", I wonder "OK, so is there and unstable version as well?" (a la how some Linux distributions classify packages as stable/unstable/testing).

Other than that detail, I support this change.

**Comment by certik** [comment]
I agree, using `Status` instead of `Version` is better I think.

**Comment by jvdp1** [comment]
I agree with the comments on `status` vs `version`. I changed the title `Version` in the specs to `Status` in [this commit](https://github.com/fortran-lang/stdlib/pull/223/commits/4754c544527b5e9b35a7ade0638c86061a282552).

**Comment by scivision** [comment]
Yes this is a good and necessary change

**Comment by jvdp1** [comment]
It seems there is an agreement on the proposed change of the structure of `stdlib`.
Thank you all for your feedback. I'll merge.

**Pull request merged**
