### PR TITLE
Style: Remove tabs from code base

### PR DESCRIPTION
**Pull request by awvwgk**
Found some occurrences of tabs, which are banned from this code base in the style guide.

### CODE REVIEW

**Review by ivan-pi — APPROVED** [review]
We don't have any GitHub action running the code through a linter do we?
Hopefully the GSoC Fortran parser project moves us in this direction. 

I know there is linter under active development at CERFACS: https://pypi.org/project/flinter/

**Comment by awvwgk** [comment]
There is the “PR-Review / review-dog / misspell” action, which I have seen in action only once flagging a false positive so far. No linting or formatter action so far. Is https://github.com/fortran-lang/stdlib/issues/3 the right place to discuss this or should we open a new issue on this?

**Comment by ivan-pi** [comment]
I would prefer to keep such technical "details" out of #3.

Your post over at https://github.com/fortran-lang/fpm/issues/197 summarizes the currently available auto-formatting tools pretty well. Maybe it is easier to first decide to adopt some CI there it can be ported to stdlib later.

**Review by milancurcic — APPROVED** [review]
Yes, this is a no-brainer. Thanks!

**Pull request merged**
