### PR TITLE
Changed filenames

### PR DESCRIPTION
**Pull request by wclodius2**
Changed filenames in test_stdlib_bitsets_64.f90 and test_stdlib_bitsets_large.f90 so that they were no longer the same. Also removed spurious blanks in error stops.

[ticket: X]

### CODE REVIEW

**Review by awvwgk — COMMENTED** [review]
Would open with `status='scratch'` and `rewind(unit)` instead of closing and reopening a named file here work better?

**Comment by wclodius2** [comment]
I have never before had a need for scratch files, but this does sound like an appropriate use for them.

**Review by awvwgk — APPROVED** [review]
This looks good to me.

**Review by LKedward — APPROVED** [review]
LGTM

**Pull request merged**
