### PR TITLE
Add testing module to allow better structuring of test suites

### PR DESCRIPTION
**Pull request by awvwgk**
*For prior discussions on this topic see https://github.com/fortran-lang/stdlib/issues/162*

This is an attempt to improve the test suite in stdlib. It uses a vendored version of [test-drive], the testing framework I wrote for fpm, named `stdlib_test` for now. It currently has the status of a testing dependency, *i.e.* the module is available in stdlib's test suite but not part of stdlib's public API, downstream projects cannot use it.

[test-drive]: https://github.com/awvwgk/test-drive
[vegetables]: https://gitlab.com/everythingfunctional/vegetables

*Why vendoring a dependency?*

- [test-drive] can be automatically fetched and included in CMake, meson and fpm projects
- embedding in the manual Makefile turned out to be difficult, I gave up on this after several attempts
- can be devendored and replaced with a proper dependency later (if make is dropped)

I'm not a fan of vendoring dependencies, but I found no better solution given the constraints of stdlib's build systems.

*Why not [vegetables]?*

- [vegetables] can be automatically fetched and included in CMake and fpm projects
- similar issue as before, we can't use it in make
- vendoring is not an option because of its dependencies

I ported the tests for `stdlib_ascii` module by replacing the `check` function of `stdlib_error` and added the test suite for the testing frame itself as well. The former uses the finalizer to check for failed tests while the latter is propagating the error back. Both will correctly report on failure, the latter approach can additionally recover and run the remaining tests as well.

I'm opening this for feedback. Let me know what you think and whether we want to adopt this testing framework.

If we agree on this approach I will move all existing tests in the new format. In a follow-up patch I would try to bundle all tests into a single test executable and allow selection of the individual suites by the framework. This simplifies the logic for setting up the tests and it be easier to adopt fypp in the test suite without over-engineering the CMake macro / make include file to generate the tests.

<details>
<summary>Output from <code>stdlib_ascii</code> tester</summary>

```
# Testing: ascii
  Starting is_alphanum_short ... (1/38)
       ... is_alphanum_short [PASSED]
  Starting is_alphanum_long ... (2/38)
       ... is_alphanum_long [PASSED]
  Starting is_alpha_short ... (3/38)
       ... is_alpha_short [PASSED]
  Starting is_alpha_long ... (4/38)
       ... is_alpha_long [PASSED]
  Starting is_lower_short ... (5/38)
       ... is_lower_short [PASSED]
  Starting is_lower_long ... (6/38)
       ... is_lower_long [PASSED]
  Starting is_upper_short ... (7/38)
       ... is_upper_short [PASSED]
  Starting is_upper_long ... (8/38)
       ... is_upper_long [PASSED]
  Starting is_digit_short ... (9/38)
       ... is_digit_short [PASSED]
  Starting is_digit_long ... (10/38)
       ... is_digit_long [PASSED]
  Starting is_octal_digit_short ... (11/38)
       ... is_octal_digit_short [PASSED]
  Starting is_octal_digit_long ... (12/38)
       ... is_octal_digit_long [PASSED]
  Starting is_hex_digit_short ... (13/38)
       ... is_hex_digit_short [PASSED]
  Starting is_hex_digit_long ... (14/38)
       ... is_hex_digit_long [PASSED]
  Starting is_white_short ... (15/38)
       ... is_white_short [PASSED]
  Starting is_white_long ... (16/38)
       ... is_white_long [PASSED]
  Starting is_blank_short ... (17/38)
       ... is_blank_short [PASSED]
  Starting is_blank_long ... (18/38)
       ... is_blank_long [PASSED]
  Starting is_control_short ... (19/38)
       ... is_control_short [PASSED]
  Starting is_control_long ... (20/38)
       ... is_control_long [PASSED]
  Starting is_punctuation_short ... (21/38)
       ... is_punctuation_short [PASSED]
  Starting is_punctuation_long ... (22/38)
       ... is_punctuation_long [PASSED]
  Starting is_graphical_short ... (23/38)
       ... is_graphical_short [PASSED]
  Starting is_graphical_long ... (24/38)
       ... is_graphical_long [PASSED]
  Starting is_printable_short ... (25/38)
       ... is_printable_short [PASSED]
  Starting is_printable_long ... (26/38)
       ... is_printable_long [PASSED]
  Starting is_ascii_short ... (27/38)
       ... is_ascii_short [PASSED]
  Starting is_ascii_long ... (28/38)
       ... is_ascii_long [PASSED]
  Starting to_lower_short ... (29/38)
       ... to_lower_short [PASSED]
  Starting to_lower_long ... (30/38)
       ... to_lower_long [PASSED]
  Starting to_upper_short ... (31/38)
       ... to_upper_short [PASSED]
  Starting to_upper_long ... (32/38)
       ... to_upper_long [PASSED]
  Starting to_upper_string ... (33/38)
       ... to_upper_string [PASSED]
  Starting to_lower_string ... (34/38)
       ... to_lower_string [PASSED]
  Starting to_title_string ... (35/38)
       ... to_title_string [PASSED]
  Starting to_sentence_string ... (36/38)
       ... to_sentence_string [PASSED]
  Starting reverse_string ... (37/38)
       ... reverse_string [PASSED]
  Starting to_string ... (38/38)
       ... to_string [PASSED]
```
</details>

<details>
<summary>Output from <code>stdlib_test</code> tester</summary>

```
# Testing: check
  Starting success ... (1/44)
       ... success [PASSED]
  Starting failure ... (2/44)
       ... failure [EXPECTED FAIL]
  Message: Non-zero exit code encountered
  Starting skipped ... (3/44)
       ... skipped [SKIPPED]
  Message: This test is always skipped
  Starting failure-message ... (4/44)
       ... failure-message [EXPECTED FAIL]
  Message: Custom message describing the error
  Starting failure-with-more ... (5/44)
       ... failure-with-more [EXPECTED FAIL]
  Message: Non-zero exit code encountered
           with an additional descriptive message here
  Starting expression ... (6/44)
       ... expression [PASSED]
  Starting expression-fail ... (7/44)
       ... expression-fail [EXPECTED FAIL]
  Message: Condition not fullfilled
  Starting expression-message ... (8/44)
       ... expression-message [EXPECTED FAIL]
  Message: index("info!", "!") == 0
  Starting expression-with-more ... (9/44)
       ... expression-with-more [EXPECTED FAIL]
  Message: Condition not fullfilled
           index("info!", "?")
  Starting real-single-abs ... (10/44)
       ... real-single-abs [PASSED]
  Starting real-single-rel ... (11/44)
       ... real-single-rel [PASSED]
  Starting real-single-nan ... (12/44)
       ... real-single-nan [EXPECTED FAIL]
  Message: Exceptional value 'not a number' found
  Starting real-single-abs-fail ... (13/44)
       ... real-single-abs-fail [EXPECTED FAIL]
  Message: Floating point value missmatch
           expected 2.00000000 but got 1.00000000 (difference: 1.00000000)
  Starting real-single-rel-fail ... (14/44)
       ... real-single-rel-fail [EXPECTED FAIL]
  Message: Floating point value missmatch
           expected 1.50000000 but got 1.00000000 (difference: 33%)
  Starting real-double-abs ... (15/44)
       ... real-double-abs [PASSED]
  Starting real-double-rel ... (16/44)
       ... real-double-rel [PASSED]
  Starting real-double-nan ... (17/44)
       ... real-double-nan [EXPECTED FAIL]
  Message: Exceptional value 'not a number' found
  Starting real-double-abs-fail ... (18/44)
       ... real-double-abs-fail [EXPECTED FAIL]
  Message: Floating point value missmatch
           expected 2.0000000000000000 but got 1.0000000000000000 (difference: 1.0000000000000000)
  Starting real-double-rel-fail ... (19/44)
       ... real-double-rel-fail [EXPECTED FAIL]
  Message: Floating point value missmatch
           expected 1.5000000000000000 but got 1.0000000000000000 (difference: 33%)
  Starting integer-char ... (20/44)
       ... integer-char [PASSED]
  Starting integer-char-fail ... (21/44)
       ... integer-char-fail [EXPECTED FAIL]
  Message: Integer value missmatch
           expected -4 but got 3
  Starting integer-char-message ... (22/44)
       ... integer-char-message [EXPECTED FAIL]
  Message: Actual value is not seven
  Starting integer-char-with-more ... (23/44)
       ... integer-char-with-more [EXPECTED FAIL]
  Message: Integer value missmatch
           expected 3 but got 0
           with an additional descriptive message here
  Starting integer-short ... (24/44)
       ... integer-short [PASSED]
  Starting integer-short-fail ... (25/44)
       ... integer-short-fail [EXPECTED FAIL]
  Message: Integer value missmatch
           expected -4 but got 3
  Starting integer-short-message ... (26/44)
       ... integer-short-message [EXPECTED FAIL]
  Message: Actual value is not seven
  Starting integer-short-with-more ... (27/44)
       ... integer-short-with-more [EXPECTED FAIL]
  Message: Integer value missmatch
           expected 3 but got 0
           with an additional descriptive message here
  Starting integer-default ... (28/44)
       ... integer-default [PASSED]
  Starting integer-default-fail ... (29/44)
       ... integer-default-fail [EXPECTED FAIL]
  Message: Integer value missmatch
           expected -4 but got 3
  Starting integer-default-message ... (30/44)
       ... integer-default-message [EXPECTED FAIL]
  Message: Actual value is not seven
  Starting integer-default-with-more ... (31/44)
       ... integer-default-with-more [EXPECTED FAIL]
  Message: Integer value missmatch
           expected 3 but got 0
           with an additional descriptive message here
  Starting integer-long ... (32/44)
       ... integer-long [PASSED]
  Starting integer-long-fail ... (33/44)
       ... integer-long-fail [EXPECTED FAIL]
  Message: Integer value missmatch
           expected -4 but got 3
  Starting integer-long-message ... (34/44)
       ... integer-long-message [EXPECTED FAIL]
  Message: Actual value is not seven
  Starting integer-long-with-more ... (35/44)
       ... integer-long-with-more [EXPECTED FAIL]
  Message: Integer value missmatch
           expected 3 but got 0
           with an additional descriptive message here
  Starting logical-default-true ... (36/44)
       ... logical-default-true [PASSED]
  Starting logical-default-false ... (37/44)
       ... logical-default-false [PASSED]
  Starting logical-default-fail ... (38/44)
       ... logical-default-fail [EXPECTED FAIL]
  Message: Logical value missmatch
           expected F but got T
  Starting logical-default-message ... (39/44)
       ... logical-default-message [EXPECTED FAIL]
  Message: Logical value is not true
  Starting logical-default-with-more ... (40/44)
       ... logical-default-with-more [EXPECTED FAIL]
  Message: Logical value missmatch
           expected F but got T
           with an additional descriptive message
  Starting character ... (41/44)
       ... character [PASSED]
  Starting character-fail ... (42/44)
       ... character-fail [EXPECTED FAIL]
  Message: Character value missmatch
           expected 'negative' but got 'positive'
  Starting character-message ... (43/44)
       ... character-message [EXPECTED FAIL]
  Message: Character string should be negative
  Starting character-with-more ... (44/44)
       ... character-with-more [EXPECTED FAIL]
  Message: Character value missmatch
           expected 'negative' but got 'positive'
           with an additional descriptive message
# Testing: select
  Starting always-pass ... (1/6)
       ... always-pass [PASSED]
  Starting always-fail ... (2/6)
       ... always-fail [EXPECTED FAIL]
  Message: Always failing test
  Starting run-good-suite ... (3/6)
       ... run-good-suite [PASSED]
  Starting run-bad-suite ... (4/6)
       ... run-bad-suite [PASSED]
  Starting run-selected ... (5/6)
       ... run-selected [PASSED]
  Starting select-missing ... (6/6)
       ... select-missing [PASSED]
```
</details>

### CODE REVIEW

**Comment by milancurcic** [comment]
Thank you for starting this, I think it has been much needed for stdlib.

**Comment by awvwgk** [comment]
We already have a sizeable test suite in stdlib, porting all tests will take a while. I'll keep this list here up-to-date with the state of this patch.

- [x] `src/tests/ascii/test_ascii.f90` (1017 lines)
- [ ] `src/tests/bitsets/test_stdlib_bitset_64.f90` (743 lines)
- [ ] `src/tests/bitsets/test_stdlib_bitset_large.f90` (1468 lines)
- [ ] `src/tests/io/test_loadtxt.f90` (63 lines)
- [ ] `src/tests/io/test_loadtxt_qp.f90` (30 lines)
- [ ] `src/tests/io/test_open.f90` (99 lines)
- [ ] `src/tests/io/test_parse_mode.f90` (187 lines)
- [ ] `src/tests/io/test_savetxt.f90` (119 lines)
- [ ] `src/tests/io/test_savetxt_qp.f90` (63 lines)
- [ ] `src/tests/linalg/test_linalg.f90` (581 lines)
- [ ] `src/tests/logger/test_stdlib_logger.f90` (845 lines)
- [x] `src/tests/math/test_linspace.f90` (422 lines)
- [x] `src/tests/math/test_logspace.f90` (272 lines)
- [x] `src/tests/math/test_math_arange.f90` (86 lines)
- [x] `src/tests/math/test_stdlib_math.f90` (223 lines)
- [ ] `src/tests/optval/test_optval.f90` (376 lines)
- [ ] `src/tests/quadrature/test_gauss.f90` (533 lines)
- [ ] `src/tests/quadrature/test_simps.f90` (505 lines)
- [ ] `src/tests/quadrature/test_trapz.f90` (236 lines)
- [ ] `src/tests/sorting/test_sorting.f90` (939 lines)
- [ ] `src/tests/stats/test_corr.f90` (387 lines)
- [ ] `src/tests/stats/test_cov.f90` (614 lines)
- [ ] `src/tests/stats/test_distribution_PRNG.f90` (108 lines)
- [ ] `src/tests/stats/test_mean.f90` (143 lines)
- [ ] `src/tests/stats/test_mean_f03.f90` (55 lines)
- [ ] `src/tests/stats/test_moment.f90` (712 lines)
- [ ] `src/tests/stats/test_rawmoment.f90` (624 lines)
- [ ] `src/tests/stats/test_var.f90` (463 lines)
- [ ] `src/tests/stats/test_varn.f90` (359 lines)
- [ ] `src/tests/string/test_string_assignment.f90` (72 lines)
- [ ] `src/tests/string/test_string_derivedtype_io.f90` (80 lines)
- [ ] `src/tests/string/test_string_functions.f90` (518 lines)
- [ ] `src/tests/string/test_string_intrinsic.f90` (489 lines)
- [ ] `src/tests/string/test_string_match.f90` (72 lines)
- [ ] `src/tests/string/test_string_operator.f90` (123 lines)
- [ ] `src/tests/string/test_string_strip_chomp.f90` (110 lines)
- [ ] `src/tests/system/test_sleep.f90` (33 lines)
- [x] `src/tests/test/test_check.f90` (886 lines)
- [x] `src/tests/test/test_select.f90` (171 lines)
- [ ] `src/tests/test_always_fail.f90` (8 lines)
- [ ] `src/tests/test_always_skip.f90` (8 lines)
- [ ] `total` (14842 lines)

**Comment by jvdp1** [comment]
Thanks @awvwgk . This is highly needed, indeed!
If everybody agree on this approach, I would be happy to help you to move all tests.

**Comment by milancurcic** [comment]
@awvwgk as an exercise and if you agree, I'd like to tackle all the tests for the io module.

**Comment by awvwgk** [comment]
@milancurcic @jvdp1 thanks for the offer, feel free to send a PR against my fork, but please ping me there or I might overlook it.

**Comment by jvdp1** [comment]
I will give it a start.

@awvwgk : is it better to keep all stats functions in different tests? Or should I merge them in a single program?

**Comment by awvwgk** [comment]
> is it better to keep all stats functions in different tests? Or should I merge them in a single program?

The testing framework should encourage writing smaller tests, such that one unit test is only testing one thing.

For now I suggest the following strategy:
1. transform internal procedures to module procedures, add an allocatable `error_type` to their interface
2. create a `collect_*` subroutine to register all unit tests, export only the `collect_*` subroutine as public
3. create a minimal driver running only the single testsuite
    (see [test-drive](https://github.com/awvwgk/test-drive) Readme or copy the driver from an already converted suite)
4. replace all `check` calls from `stdlib_error` with the ones from `stdlib_test`, relevant signature change:
    - first argument is the `error_type`
    - remove `warn` argument
    - `msg=` keyword argument becomes positional argument after testing condition
    - keep the condition our use a more specific `check` procedure
      (see [test-drive](https://github.com/awvwgk/test-drive) Readme for all available ones)
5. run the testsuite, everything should compile and pass now
6. add `if (allocated(error)) return` between the checks or split the unit tests to smaller checks

Don't spend to much time on step 3, we will refactor all driver programs at a later point to become more flexible.

**Comment by jvdp1** [comment]
@awvwgk , an additional question: it seems that it is not possible to check if 2 (float) arrays are the same. should I use the boolean check? Or should I extend check_float to higher dimensions?

**Comment by awvwgk** [comment]
> an additional question: it seems that it is not possible to check if 2 (float) arrays are the same. should I use the boolean check? Or should I extend check_float to higher dimensions?

Using a boolean check for now seems best. I prefer to only change one thing at a time to keep patches small. This one will already be huge patch, because we have to go through all the tests, therefore I would defer implementing new features to the test framework at the moment.

I was planning to transfer the *test-drive* project to @fortran-lang when it is used in stdlib and fpm. Than we can develop its capabilities further. Checks on arrays are a bit more difficult because there are different possible ways to define a threshold, therefore I would like to discuss this first before implementing something ad-hoc.

**Comment by milancurcic** [comment]
I opened a PR with io tests here: https://github.com/awvwgk/fortran-stdlib/pull/87 (just in case there were no notifications, I'm new to this workflow).

The tests there won't pass with ifort until #506 is merged. I think there are two ways forward:

1. Temporarily disable `test_loadtxt` and `test_savetxt` and merge https://github.com/awvwgk/fortran-stdlib/pull/87. Once done, merge this into master. Then merge #506 with tests enabled (pending the approval of the fix).
2. Merge #506 into  https://github.com/awvwgk/fortran-stdlib/pull/87, then merge that here. Once done, merge into master.

**Comment by awvwgk** [comment]
I think it is best to target #506 against this branch, since this PR is anyway quite large already and touching a lot of things. We can discuss the change in #506 first to give it a proper review, but since it is fixing an actual bug, I think we can move it forward a little bit faster.

**Comment by milancurcic** [comment]
I opened https://github.com/awvwgk/fortran-stdlib/pull/90 which addresses the failing ifort tests.

**Comment by awvwgk** [comment]
I rebased this commit and cleaned up the history to make it easier to review. Since it is still a huge PR I recommend to review it commit by commit and  without showing whitespace changes in the diff. You can go to the [commits](https://github.com/fortran-lang/stdlib/pull/494/commits) tab and start reviewing there, but I will also link all commits below with short explanation.

The most important part to review  is the addition of [test-drive] (called `src/tests/stdlib_test.fypp`) and the required CMake and make infrastructure. An additional `fortran_stdlib_testing` library is generated which depends on `fortran_stdlib` proper and used for linking the tests. Finally, it contains it adds it own native tests (`src/tests/test`) and a port of (`src/tests/ascii`). See [`ead119d`](https://github.com/fortran-lang/stdlib/pull/494/commits/ead119d68f2e0d5fc412ca2dbff7ebf9bfbe5adb?diff=unified&w=1).

This should give a good overview over the main changes in this PR, especially regarding the build system and the testing framework setup.

[test-drive]: https://github.com/awvwgk/test-drive

We have a couple of separate commits porting one test file or test directory at a time (list below is sorted, not chronological). I don't think those need a detailed review, because we can check them easily by running them. Still, we had quite some different styles in our tests and the commits below show how the different styles are ported to more uniform structure. Also it shows that we can use the new testing framework for almost all of our tests.

- math/math [`4b7720b`](https://github.com/fortran-lang/stdlib/pull/494/commits/4b7720b14c7ab944e481087d4f6d8a20ab84b1d5?diff=unified&w=1)
- bitset/bitset_64 [`703239e`](https://github.com/fortran-lang/stdlib/pull/494/commits/703239e8e1afd1a59c30e4688144453db64d059f?diff=unified&w=1)
- bitset/bitset_large [`8f79e5b`](https://github.com/fortran-lang/stdlib/pull/494/commits/8f79e5b9b19265af376f56bb798e6fb6acc5a297?diff=unified&w=1)
- linalg/linalg [`7d4b0f7`](https://github.com/fortran-lang/stdlib/pull/494/commits/7d4b0f7f0a5494b03f547769fa20fdd8204a9501?diff=unified&w=1)
- optval/optval [`e92bc71`](https://github.com/fortran-lang/stdlib/pull/494/commits/e92bc71bf874ef9019e5bc7f92195da7e0043821?diff=unified&w=1)
- string/* [`056d992`](https://github.com/fortran-lang/stdlib/pull/494/commits/056d992c8286ad6c17a939cecd67347fadc8f1d4?diff=unified&w=1)
- stats/mean [`8427418`](https://github.com/fortran-lang/stdlib/pull/494/commits/8427418199e3f5e083da9102ea0324666a3a7d64?diff=unified&w=1)
- stats/mean_f03 [`2889964`](https://github.com/fortran-lang/stdlib/pull/494/commits/28899642eb9175fd896ed90134b75b301c4456b7?diff=unified&w=1)
- stats/median [`adc86dd`](https://github.com/fortran-lang/stdlib/pull/494/commits/adc86dd3751cb08f51ef1cb16f6e1a15cf6fba99?diff=unified&w=1)
- stats/rawmoment [`71dc8c5`](https://github.com/fortran-lang/stdlib/pull/494/commits/71dc8c54e0d903cf1926b2699d6cd5b493af386d?diff=unified&w=1)
- stats/variant [`0945d7b`](https://github.com/fortran-lang/stdlib/pull/494/commits/0945d7b4f41e63da148afeb4e5be86c67ac9a252?diff=unified&w=1)
- quadrature/* [`33b4df2`](https://github.com/fortran-lang/stdlib/pull/494/commits/33b4df2faee7b383feb59711ceef1d6b5b6e1bc8?diff=unified&w=1)
- io/* [`9d54d58`](https://github.com/fortran-lang/stdlib/pull/494/commits/9d54d5834cc27424f235b19dac2f0d5bbc79a4e5?diff=unified&w=1)

While some tests are still missing, I think I'm done with porting tests for now and we can start reviewing. The missing tests can be done in later PRs unless there is a request that we should do all of them now.

Finally, there is the bugfix from #506 on top.

- portable loadtxt/savetxt [`58b8467`](https://github.com/fortran-lang/stdlib/pull/494/commits/58b84677d4aa6132658509539718db42ebbc4e8b?diff=unified&w=1)

**Comment by certik** [comment]
Ok. I started reviewing, it will take me some time. I also need to test this by hand. I'll try to get this done soon. @milancurcic, @LKedward, @everythingfunctional and others, if you can help with reviewing this PR, that would be very helpful.

**Comment by milancurcic** [comment]
Thank you @certik, IMO the best way to review this is to port one or more of the remaining tests. In doing that you'll also look at the already ported tests as an example, as well as run them by hand.

**Comment by everythingfunctional** [comment]
I might have time Wednesday or Thursday to look a little closer at this. I'll do as @milancurcic suggests and try to port one of the sets of tests.

**Comment by awvwgk** [comment]
> I might have time Wednesday or Thursday to look a little closer at this.

Thanks Brad, I'm really looking forward to your feedback.

**Comment by everythingfunctional** [comment]
I don't think I'm going to have enough time to do as thorough a review as I'd like to, but I was able to give it enough to provide some general impressions and observations. First, I don't have harsh criticisms, if anything ideas for future improvements. And there are some things I like about it. First the good.

The organization and "operation" of the tests is reasonable. It took me a second to find right-side up, but once I saw it, it made enough sense. I also can see the value in having different sections of the test suite in separate executables, even if it wasn't my first instinct.

Having the framework report information about the values were checked is a good thing. It helps to provide concrete examples to things that can otherwise feel a bit abstract, and it's why I wanted the capability when I implemented vegetables.

My criticisms are in the "documentation;" e.g. descriptions of the tests, and their readability. When executing the test suite, I can see the modules and procedures that are being tested, but I don't get much of an understanding of the expected behavior of those modules or how they are intended to be used. Granted it's not easy, but a really high quality and valuable test suite can provide this. If you're attending FortranCon in a couple of weeks I hope to convey this kind of strategy in my talk. If not, I can recommend a [great talk by Kevlin Henney](https://www.youtube.com/watch?v=tWn8RA_DEic).

Given the above, I didn't find it particularly intuitive trying to follow a given test case. If you get the above right, this gets easier, because a reader can have a clear "story" in mind when trying to follow the logic of a test case. But another aspect that didn't make it easy (and I may just have missed it) was that almost all of the checking of expected vs actual was done via a single generic interface, `check`. This is too vague and generic. Be more specific about what your checking and for what, and it will be easier to see the why.

### Philosophical Discussion

There is value in writing a test suite alone; as an exercise for the developer to play around with the interfaces, and as a cross check that the implementation behaves as expected. I think this test suite has more than likely achieved that. But for really big return on investment a test suite should serve as a resource to future contributors and make it easier for them to understand the code. I think there is a bit to be desired on that front. I think it's achievable with the infrastructure you're putting in place here with just a bit of tweaking and some vision towards that goal.

I'm sorry that I don't have time (at least right now) to provide a lot of contributions in that direction, but I'm happy to provide guidance and suggestions to anybody who wants to hear it and wants to put in the effort.

**Comment by awvwgk** [comment]
Keeping this PR up-to-date and reviewable is quite a bit of work, which I have done now a couple of times (four times from the number of force pushes). We have again merge conflicts here and will most likely introduce new ones with every patch merged, which is an unfortunate side effect of a large refactoring like this.

Therefore, I'll stop updating this PR for now. It is of course still reviewable and I appreciate any feedback here.

**Comment by jvdp1** [comment]
> Keeping this PR up-to-date and reviewable is quite a bit of work, which I have done now a couple of times (four times from the number of force pushes). We have again merge conflicts here and will most likely introduce new ones with every patch merged, which is an unfortunate side effect of a large refactoring like this.
> 
> Therefore, I'll stop updating this PR for now. It is of course still reviewable and I appreciate any feedback here.

Could we already merge this one? stdlib would then include to types of tests, but at least new PRs could use this structure, instead of the old one.

**Comment by milancurcic** [comment]
Instead, why don't we put on hold other PRs and focus on this one? If others agree, I will focus on finishing this PR until it's done, and it looks like we are almost there.

**Comment by milancurcic** [comment]
I would be okay with what @jvdp1 suggested, to merge this PR with what it currently covers, and deal with the rest in later PRs. But it would be nice to port all tests first, if feasible.

**Comment by awvwgk** [comment]
> Instead, why don't we put on hold other PRs and focus on this one? If others agree, I will focus on finishing this PR until it's done, and it looks like we are almost there.

Sorry, I won't be able to dedicate my time for porting the rest of the tests at the moment.

**Comment by milancurcic** [comment]
That's fine, you ported so many already.

**Comment by awvwgk** [comment]
I think there is some value in getting this PR merged, since it will make the testing framework available, port the largest share of the test and allow us to port the rest of the tests without risking merge conflicts in smaller PRs.

From my side this PR is complete and ready for review. As described above, I have plans for following up once it is merged.

**Comment by milancurcic** [comment]
@awvwgk I brought this branch up to date with master and resolved conflicts.

There's an outstanding issue with fpm deployment that I need some advice on. The issue currently is that `stdlib_test.fypp` which provides the test-drive to stdlib, is located in `src/tests` so it's not picked up by the fpm-deployment.sh:

https://github.com/fortran-lang/stdlib/blob/d14fca8e7cc36ed5f6f84d2bf576c91c2e54eb07/ci/fpm-deployment.sh#L34-L39

so when the CI runs `fpm test` we get:

```
<ERROR>*cmd_run*:targets error:Unable to find source for module dependency: "stdlib_test" used by "test/test_check.f90"
```

I see a few solutions:

1. Set `-maxdepth 2` so that the script picks up `src/tests/stdlib_test.{fypp,f90}`; I think this is the simplest "hack" around this problem.
2. Move `stdlib_test.fypp` from `src/tests` to `src`. This goes against your original rationale to make this internal to stdlib and not part of the public API.
3. Do not include `stdlib_test.fypp` in the fpm deployment, but add a dependency on fortran-lang/test-drive in fpm.toml, assuming the API is the same between test-drive and stdlib_test.fypp. This would of course, require renaming all imports in current tests from `stdlib_test` to `testdrive`.

I think 3rd is the best approach but a little bit more work. What do you think?

And if so, should we sort that out in this PR, or do a quick fix here (option 1) and then have a separate PR to switch to test-drive as an fpm dependency?

**Comment by awvwgk** [comment]
Let's go with option 3, I opened https://github.com/fortran-lang/test-drive/pull/6 to make test-drive aware of quadruple precision and started working on a solution in https://github.com/awvwgk/fortran-stdlib/pull/103.

For using test-drive directly we have to:

- [x] allow make to dynamically fetch the test-drive source
- [x] allow cmake to dynamically fetch or find a system package to make test-drive available
- [x] update the fpm generator to depend on test-drive

**Comment by awvwgk** [comment]
We might have to increase the threshold for the sleep test on MacOS a bit further:

```
      Start 37: sleep
37/46 Test #37: sleep ............................***Failed    0.27 sec
# Testing: sleep
  Starting sleep ... (1/1)
       ... sleep [FAILED]
  Message: Floating point value missmatch
           expected 100.00000000000000 but got 230.29599999999999 (difference: 130%)
1 test(s) failed!
```

**Review by jvdp1 — APPROVED** [review]
OK for me as it is currently.
I have no time now to move the remaining tests on stats. An issue might be assigned to me when merging this PR.

**Comment by awvwgk** [comment]
Many thanks to everybody who contributed to this project. To move forward, I'll go ahead and merge this PR now.

**Pull request merged**
