### PR TITLE
Add module for list of strings

### PR DESCRIPTION
**Pull request by arjenmarkus**
The API for the module to manipulate lists of strings has been discussed and this has resulted in the current implementation.

Hm, I cloned the repository via GitHub desktop, but it seems it is part of the original repository. I hope this works anyway.

### CODE REVIEW

**Comment by milancurcic** [comment]
Thanks @arjenmarkus but this is still from a branch on stdlib. Can you please follow these steps:

1. Fork this repo (fortran-lang/stdlib). You will now have arjenmarkus/stdlib.
2. In GitHub Desktop, clone your fork (arjenmarkus/stdlib), not fortran-lang/stdlib
3. Create a new branch in it (for example, string-list), and commit your changes to that branch
4. Open a new Pull Request in fortran-lang/stdlib, based on the string-list branch in arjenmarkus/stdlib.

**Comment by arjenmarkus** [comment]
Thanks - I hope I get it right this time when I try this receipe. (I will
keep my fingers crossed!)

Op do 4 feb. 2021 om 03:52 schreef Milan Curcic <notifications@github.com>:

**Comment by arjenmarkus** [comment]
I do not understand this: I made a fork, I said in Github that I only want
to use the repository locally (no automatic sharing with the original
repository), so I thought I would have to create pull requests explicitly
and have it completely independent otherwise from the fortran-lang/stdlib
repository, but still it put in my corrections of a typo automatically. I
am getting a trifle paranoid here.

Op do 4 feb. 2021 om 09:17 schreef Arjen Markus <arjen.markus895@gmail.com>:

**Comment by milancurcic** [comment]
@arjenmarkus If you'd like, we can get on a quick Zoom call so that we go through this process together with a screen share.

**Comment by arjenmarkus** [comment]
@Milan Curcic <caomaco@gmail.com>, that sounds like a good idea, because I
am really lost here :(

Op do 4 feb. 2021 om 23:01 schreef Milan Curcic <notifications@github.com>:

**Pull request closed without merging**
