### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by MarDiehl**
looks like a typo...

### CODE REVIEW

**Review by awvwgk — APPROVED** [review]
Nice catch. Thanks.

**Comment by zbeekman** [comment]
Oopsies! LGTM! (But I can't seem to provide a review... let me refresh the page and see if that might be why)

**Review by zbeekman — APPROVED** [review]
Sorry about the typo! Thanks for the PR!

**Comment by milancurcic** [comment]
Thanks, all!

**Pull request merged**
