### PR TITLE
remove docs/API.md

### PR DESCRIPTION
**Pull request by milancurcic**
Minimal PR to test docs deployment.

### CODE REVIEW

**Comment by zbeekman** [comment]
LGTM.

**Comment by zbeekman** [comment]
well, actually, if you want to test the deployment,  you may need my PR...

**Comment by milancurcic** [comment]
Yes, I'm waiting for yours to finish and then merge it into this.

**Comment by zbeekman** [comment]
I just pushed again removing the file on my branch, hope that's ok.

**Comment by milancurcic** [comment]
Actually, your PR is sufficient to prove that it works. If your merged PR keeps the CNAME, then this PR not needed and I will close it.

**Pull request closed without merging**
