### PR TITLE
Bugfix release version 0.2.1

### PR DESCRIPTION
**Pull request by awvwgk**
The various build system patches after the 0.2.0 release might warrant a small bugfix release. Please create a new tag v0.2.1 if merged.

### CODE REVIEW

**Comment by kjelljorner** [comment]
Would be great to have this approved and merged as these build problems current [prevent](https://github.com/conda-forge/libconeangle-feedstock/pull/4) me from deploying libconeangle to osx arm64 on conda-forge.

**Review by milancurcic — APPROVED** [review]

**Review by ivan-pi — APPROVED** [review]

**Comment by ivan-pi** [comment]
Do I get this right, after merging I just need to go to the release page (https://github.com/fortran-lang/stdlib/releases) and click on "Draft a new release" and copy-paste (and adapt) the CHANGELOG for the Release description?

**Comment by awvwgk** [comment]
You can also autogenerate the release notes from the merged pull requests (there is a button on the top right), this is what @jvdp1 did for the v0.2.0 release.

**Comment by milancurcic** [comment]
Done, it was very easy. Thanks @awvwgk for guiding.

**Comment by awvwgk** [comment]
For future reference, here is the release guide for fpm: https://github.com/fortran-lang/fpm/wiki/Release-Process, we might create something similar for stdlib, especially for the release aftermath.

**Pull request merged**
