### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by awvwgk**
Should we require every PR to add an entry to the changelog as well? This way we avoid a lot of work collecting those before a new release and also keep the changelog an up-to-date source of new features in stdlib.

Note: I just realized I should have added the npy format to the changelog after I hit the merge button

### CODE REVIEW

**Review by milancurcic — APPROVED** [review]
Good idea, I agree.

**Review by jvdp1 — APPROVED** [review]
good idea. I agree. How to make sure we will not forget it?

**Comment by milancurcic** [comment]
We document it in the [contributing guide](https://github.com/fortran-lang/stdlib/blob/master/CONTRIBUTING.md#general-guidelines) and [workflow docs](https://github.com/fortran-lang/stdlib/blob/master/WORKFLOW.md). There we should ask for 1) tests, 2) specs, and 3) changelog update for all feature PRs.

**Comment by awvwgk** [comment]
Added a sentence to the contributing guidelines.

**Pull request merged**
