### PR TITLE
Addition of TOCs in Markdown files

### PR DESCRIPTION
**Pull request by jvdp1**
Some specs already contain multiple functions. So I thought it could be good to add TOCs for clarity.
Of course, it can be discussed/modified/removed, as usual.

### CODE REVIEW

**Comment by nshaffer** [comment]
Nothing obviously amiss, except the vim plugin magic comment thing. 

Links for each routine are obviously useful and good to have. Subsection links (Description, etc.) don't seem useful, though.

**Comment by jvdp1** [comment]
> Nothing obviously amiss, except the vim plugin magic comment thing.
> 
> Links for each routine are obviously useful and good to have. Subsection links (Description, etc.) don't seem useful, though.

Thanks @nshaffer for the review. I will remove Vim comments and subsection links (Their are indeed all the same).

**Comment by certik** [comment]
Looks good to me.

**Comment by jvdp1** [comment]
> Looks great! My only suggestion is to remove the "Implemented" heading from the top of each spec file--it serves no purpose, and in some files it's incorrect (for example, in quadrature it lists some functions that aren't implemented).

Thank you @milancurcic. Suggestion applied.

**Comment by jvdp1** [comment]
Ok. I will merge. Thank you for your comments.

**Pull request merged**
