### PR TITLE
Export symbols on Windows and set PIC flag for Unix

### LINKED ISSUE #644: Position independent code
I came across an issue with statically linking stdlib as a dependency for a shared library target. In the end, I [solved](https://github.com/kjelljorner/libconeangle/blob/c81430584225e76b3673176ffdca7e5050151931/CMakeLists.txt#L27) it by setting the `POSITION_INDEPENDENT_CODE` property for the `fortran_stdlib` target:

```cmake
set_target_properties(fortran_stdlib PROPERTIES POSITION_INDEPENDENT_CODE ON)
```

One idea would be to always set this property, but as I understand this could also lead to performance issues.

### PR DESCRIPTION
**Pull request by awvwgk**
More CMake stuff

Closes #644 
See #645

### CODE REVIEW

**Comment by kjelljorner** [comment]
I was going to put in the pull request but saw that you beat me to it! Would have missed `WINDOWS_EXPORT_ALL_SYMBOLS` though – good catch!

**Review by milancurcic — APPROVED** [review]
Thanks!

**Review by kjelljorner — APPROVED** [review]

**Comment by kjelljorner** [comment]
Sorry for the tardy review; was on a conference this week

**Comment by awvwgk** [comment]
Thanks for having a look. With two approvals I'll go ahead and merge.

**Pull request merged**
