### PR TITLE
Remove `msys` from CI and install `fypp` via msys2 package

### PR DESCRIPTION
**Pull request by minhqdao**
- [x] Remove `msystem: msys` from CI.
- [x] Install `fypp` via msys2 package instead of `pip`.

Address https://github.com/fortran-lang/stdlib/issues/853.

### CODE REVIEW

**Comment by zoziha** [comment]
@minhqdao, thank you for your sharing. 

As far as I knowA, [`msystem:MSYS` does not have the fypp package](https://packages.msys2.org/base/mingw-w64-python-fypp). In this PR, `msystem:MSYS` will actually use the tools of the `msystem:MINGW64` environment, that is to say, `msystem:MSYS` has no actual effect for CI testing. Combined with the topic of #853, `msystem:MSYS` should be removed.

I have been a user of MSYS2 for few years. I believe that `msystem:MSYS` was originally only used to provide an initial Unix-like compilation environment and tools for other environments, and almost no one will use it as a development environment.

It is sufficient for `Stdlib` to use `msystem:MINGW64`, `msystem:UCRT64`, and `msystem:CLANG64`. `MSYS2` also plans to abandon the 32-bit environment, so we should remove the tests of `msystem:MSYS` and the 32-bit environment (maybe later); Since `Flang` and `LFortran` in the `msystem:CLANG64` environment are not ready yet, `CLANG64` does not need to be supported at present.

**Comment by minhqdao** [comment]
I see, it was probably not the best idea to merge the two setups then – I can revert that. In fact, the idea for this PR was only to fix the setup for `msystem: mingw64`. So we can still do that and leave `msystem: msys` as is for now because it is still working. If there's a consensus on removing `msys` entirely, I'm happy to do that in a separate PR.

**Comment by minhqdao** [comment]
Ok, I see it was `msystem: msys` which failed. Let's probably remove it then.

**Review by zoziha — APPROVED** [review]
@minhqdao, thanks, LGTM.

**Comment by minhqdao** [comment]
Will merge this so the CI stops failing. If there's ever the need to bring back `msystem: msys`, we can do https://github.com/fortran-lang/stdlib/issues/853#issuecomment-2302798585.

**Pull request merged**
