### PR TITLE
add missing implicit none, set compiler flags to force implicit none

### PR DESCRIPTION
**Pull request by scivision**
also set minimum CMake version to 3.14 per prior discussion and add example check requiring CMake 3.14: real128

### CODE REVIEW

**Comment by certik** [comment]
I've never used `-fimplicit-none`. Should that be recommended to be used by default for all modern Fortran projects?

**Comment by scivision** [comment]
yes `-fimplicit-none` was available at least back to Gfortran 4.1 (didn't try looking further back) and I don't think there are any drawbacks.

**Comment by certik** [comment]
@scivision cool. This is relevant to: https://github.com/j3-fortran/fortran_proposals/issues/90.

**Comment by certik** [comment]
Thanks for the improvements!

**Comment by zbeekman** [comment]
Thanks all!

**Pull request merged**
