### PR TITLE
Preparation for 0.5.0 release

### PR DESCRIPTION
**Pull request by jvdp1**
PR to prepare the release fo `v0.5.0`

### CODE REVIEW

**Review by gnikit — APPROVED** [review]
Amazing thanks @jvdp1

**Review by perazz — APPROVED** [review]
Great idea to release a new version to clearly mark the addition of linear algebra backends. Good job @jvdp1, thank you!

**Comment by jvdp1** [comment]
@perazz suggested [here] to wait on #774 before releasing [v0.5.0]. It is ok for me. @perazz do you still think so? @gnikit?

**Comment by perazz** [comment]
@jvdp1 @gnikit I think it would make sense in preparation of the linear algebra implementation, but it is functionally not necessary, as 0.5.0 will have no high-level linear algebra functions yet.

**Comment by gnikit** [comment]
Yeah, I am okay to hold this. I will review #774 over lunch today and then we can issue a release.

**Review by perazz — APPROVED** [review]

**Comment by jvdp1** [comment]
> @jvdp1 do you know if we fixed the file extension capitalisation Issue that introduced with the cpp preprocessor? If so I think we should fix first and then release.

I believe it was solved with #787 and #790. @perazz can you confirm it, please?

**Comment by perazz** [comment]
> solved with #787 and #790.

Exactly

**Comment by jvdp1** [comment]
> > solved with #787 and #790.
> 
> Exactly

Thank you @perazz for the confirmation. I will generate a new release, and I let you advertize this new version (mainly your work) on Discourse.

**Comment by perazz** [comment]
Great! Thank you @jvdp1.

**Pull request merged**
