### PR TITLE
Progress on loadtxt and savetxt (proposition)

### PR DESCRIPTION
**Pull request by jvdp1**
@certik 
*I modified the subroutines for sp to avoid a temporary copy of the input/output array in dp. This approach would have been aslso difficult to extent to qp.
*I added two subroutines for qp.

@all:
To be discussed:
*For loading, I implemented two ways: 1)copy-paste of the subroutines and changing the precision and 2)unlimited polymorphic objects. We need to decide which approach to use.
*I would be happy to extent loadtxt and savetxt to integer (1,4,8,16). Is there a way to do it automatically? Or should I repeat it manually (all subroutines will be the same, except for the type of the arrays)?
*Should we add other options, like presence of an header, max columns/rows to load,... (similar to Numpy)?

### CODE REVIEW

**Comment by certik** [comment]
Thanks a lot for this work! My comments:

1. Would you mind merging in the latest master to pick up the CI tests?

2. Before we merge this, we should polish up the history (it seems to have my old commits that are already in master, etc.)

3. The refactoring to `number_of_columns` and `number_of_rows_numeric` is good. 

4. Adding `qloadtxt` and `qsavetxt` is good.

5. Regarding the `savetxt_poly`, that's an interesting idea. My comments are: a) do all compilers support this on all platforms? b) Will the compiler messages be clear if the user passes in incorrect / unsupported type? c) The public API should be just `savetxt`, not `savetxt_poly`.

6. There are tools that people have mentioned that allow to generate code from a template. In something like this, when the code is literally the same, just the type changes, It might make sense to use them in this case.

7. I suggest you split this PR into two. In one PR do 1., 2., 3., 4. Then I can pretty much review & merge right away. In the other PR do 5. and we can discuss the various pros and cons. It might take some time to reach an agreement.  In some future PR, we can also implement 6.

**Comment by certik** [comment]
The branch is quite messed up. For some reason GitHub shows a diff against the CI file, which it should not. 

First of all, you should be using a branch in your repository other than master.

Here is how you can work. First fix your remotes. Here are mine:
```
$ git remote -v
ondrej	git@github.com:certik/stdlib.git (fetch)
ondrej	git@github.com:certik/stdlib.git (push)
origin	https://github.com/fortran-lang/stdlib.git (fetch)
origin	https://github.com/fortran-lang/stdlib.git (push)
```
So do
```
git remote add jvdp1 git@github.com:jvdp1/stdlib.git
```
and if your `origin` does not point to https://github.com/fortran-lang/stdlib.git, do:
```
git remote rename origin old-origin
git remote add origin https://github.com/fortran-lang/stdlib.git
```

Then once your remotes are fixed, do from your current master:
```
git checkout -b loadtxt
git fetch origin master:master
git merge master
git push jvdp1 loadtxt
```
This will create a branch `loadtxt` from your current master, then merge the actual origin master, and finally push into your fork. Then you can create a new PR from it and things should start looking much better.

**Comment by jvdp1** [comment]
@certik Thank you for the procedure. I just followed it, and here is the result:

```
$ git remote -v
jvdp1	https://github.com/jvdp1/stdlib.git (fetch)
jvdp1	https://github.com/jvdp1/stdlib.git (push)
origin	https://github.com/fortran-lang/stdlib.git (fetch)
origin	https://github.com/fortran-lang/stdlib.git (push)
$ git branch -a
* loadtxt
  master
  remotes/jvdp1/HEAD -> jvdp1/master
  remotes/jvdp1/io
  remotes/jvdp1/loadtxt
  remotes/jvdp1/master
  remotes/origin/master

```

Should I close this PR, and create a new one from loadtxt?

**Comment by certik** [comment]
Keep this one open for now. But create a new one from the `loadtxt` branch.

**Comment by jvdp1** [comment]
> Keep this one open for now. But create a new one from the `loadtxt` branch.

I am afraid that if I do a PR from loadtxt, it will still have all the commits.

**Comment by certik** [comment]
If you want, I can push a branch that's polished and you can then pull it and create a PR from it.

**Comment by jvdp1** [comment]
> If you want, I can push a branch that's polished and you can then pull it and create a PR from it.

Ok. Let 's do that.

**Comment by certik** [comment]
There you go:
```
git fetch https://github.com/certik/stdlib loadtxt2:loadtxt2
git checkout loadtxt2
git push jvdp1 loadtxt2
```

**Comment by jvdp1** [comment]
> There you go:
> 
> ```
> git fetch https://github.com/certik/stdlib loadtxt2:loadtxt2
> git checkout loadtxt2
> git push jvdp1 loadtxt2
> ```

Thanks @certik for your help. Not sure what you did but it worked. See the new PR.

**Comment by certik** [comment]
All I've done is to take your branch (master), put it into a new branch `loadtxt2`, and then I merged with "master" (the latest official master) and then I did `git reset master`, which squashed all the commits, and then `git commit -a --author="..."` and that's it.

**Pull request closed without merging**
