### PR TITLE
CMake: introduce ADDTEST macro

### PR DESCRIPTION
**Pull request by certik**
This simplifies the CMake code a lot.

@zbeekman let me know if this goes in the direction that you prefer with CMake.

### CODE REVIEW

**Comment by scivision** [comment]
That seems like a nice macro, particularly since so many tests have that pattern

**Comment by certik** [comment]
Thanks for the review!

**Comment by zbeekman** [comment]
@certik nice one! Yes, this is exactly the sort of thing I would have done myself. I'm not 100% sure about having it as a macro instead of a function, but we can iterate on that idea later. Great starting point!

**Comment by certik** [comment]
@zbeekman go ahead and create a function. I didn't even know you can create functions in CMake.

**Pull request merged**
