### PR TITLE
CI: Add automatic PR review for misspellings

### PR DESCRIPTION
**Pull request by zbeekman**
Add bot to post comments/reviews on PRs for misspelling issues using [reviewdog/action-misspell](https://github.com/reviewdog/action-misspell)

A new token may need to be created to allow comments to be posted on PRs instead of just PR status. This would have caught typos in my previous PRs. Token info is here: https://github.com/reviewdog/reviewdog#reporter-github-pullrequest-review-comment--reportergithub-pr-review

### CODE REVIEW

**Comment by certik** [comment]
This is what I see in the test:

Screenshot_2019-12-31 CI Add automatic PR review for misspellings by zbeekman · Pull Request #56 · fortran-lang stdlib

Does that mean it passed it? How does it look like when it fails?

Can you please rebase on top of the latest master, so that we can merge it?

**Comment by zbeekman** [comment]
@certik: With the token setup correctly, it will comment in the PR if it detects misspellings in changed files:

rd-image

No need to check the CI output by hand. We may need to create a new token and set it in the repo's secrets. I will rebase this onto master soon, but I need to run out for a moment right now.

**Comment by certik** [comment]
Do you know how often this has false positives? Say reporting some correctly spelled Fortran variable names as misspelled?

**Comment by zbeekman** [comment]
> Do you know how often this has false positives? Say reporting some correctly spelled Fortran variable names as misspelled?

In my experience this almost never happens. It doesn't change the PR status just posts comments on the code, so false positives can be easily ignored. If it becomes an issue we can always remove it.

**Comment by certik** [comment]
@zbeekman you should have push access and other rights to the repository. Go ahead and set this up if you have time.

Let's try it, and if it works, great. If it doesn't work for us, we can remove it later.

**Comment by zbeekman** [comment]
> Looks good to me. I'll leave it to you @zbeekman to merge and to set this up if some token has to be setup.

Great, and if it ever has too many false-positives, etc. we should disable it or tweak the scope.

One small issue regarding tokens: I'm happy to provide a personal access token with the correct scopes, however to add the secret to the repository someone with greater privileges (admin I think) will need to do so.

**Comment by certik** [comment]
Send me the token by email and I'll put it there.

**Pull request merged**
