### PR TITLE
Enforce fortran syntax highlighting on fypp files

### LINKED ISSUE #185: Add syntax highlighting to fypp source files
Since fypp is not officially supported:

- https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

It could be worthwhile to override syntax hightlighting in github. It would make it easier to browse the source code online. See:

- https://github.com/github/linguist#overrides
- github/linguist#1792

To do this one could add a `.gitattributes` file:
```
 *.fypp linguist-language=fortran 
```

Thoughts?

### PR DESCRIPTION
**Pull request by ashwinvis**
Fixes #185

### CODE REVIEW

**Comment by certik** [comment]
Thanks @ashwinvis !

**Comment by certik** [comment]
How does it work? I don't see any change here:

https://github.com/fortran-lang/stdlib/blob/8be4bc0db4417bfe90b60e5e4d671e3047cd557a/src/stdlib_experimental_io.fypp

**Comment by ashwinvis** [comment]
Beats me... some other files work though:

- https://github.com/fortran-lang/stdlib/blob/ce987d2a4a215d8410f809cc1510d7eac24bd11d/src/common.fypp
- https://github.com/fortran-lang/stdlib/blob/ce987d2a4a215d8410f809cc1510d7eac24bd11d/src/stdlib_experimental_optval.fypp

**Comment by certik** [comment]
Weird. Your change should not hurt anything, so we'll keep it.

**Pull request merged**
