### PR TITLE
CI(gha): test w/ multiple GFortrans & macOS too

### PR DESCRIPTION
**Pull request by zbeekman**
Replaces #30 

Test GFortran 7,8 & 9 on macOS and Linux

Also, install newer CMake on CI using pip.

### CODE REVIEW

**Comment by zbeekman** [comment]
@certik This should be ready for review

**Comment by zbeekman** [comment]
I'd like to rebase on the latest commits, and switch to out of source build. But I can do the latter in a separate PR I guess.

**Comment by certik** [comment]
This looks great! Thank you. Yes, if you could rebase on top of the latest master, just in case.

Then in separate PR after this is merged, we can get it working in out of tree builds.

**Comment by milancurcic** [comment]
Fantastic! Good to merge IMO.

**Comment by zbeekman** [comment]
@certik @milancurcic rebased on latest master

**Comment by certik** [comment]
It's in! Thanks a lot @zbeekman, this is super helpful. Now we just need to get Windows covered, and we'll be in good shape.

**Pull request merged**
