### PR TITLE
Add spec for optval

### PR DESCRIPTION
**Pull request by nshaffer**
I based this on the structure of the spec for `mean`. Things I'm not 100% sure of

- Is an "implemented" section necessary for this case?
- Do we want language-defined terms capitalized or formatted some other way, e.g., PRESENT vs present vs `present`?
- Is my mixed usage of "default" and "fallback" a problem?

### CODE REVIEW

**Comment by jvdp1** [comment]
Thank you.

> I based this on the structure of the spec for `mean`. Things I'm not 100% sure of
> 
> * Is an "implemented" section necessary for this case?

I suggest to keep it; to follow the same format as other specs.

> * Do we want language-defined terms capitalized or formatted some other way, e.g., PRESENT vs present vs `present`?

I think it is @milancurcic who mentioned that, for the `mean` spec, he preferred e.g., `present` over PRESENT. I tried to follow that rule for the other specs.

> * Is my mixed usage of "default" and "fallback" a problem?

I am ok with it.

**Comment by milancurcic** [comment]
Alternatively, to avoid confusion regarding what "present" means, we could write:

> Returns `x` if `present(x)` returns `.true.`, otherwise `default`.

instead of

> Returns `x` if it is present, otherwise `default`.

**Comment by nshaffer** [comment]
Thanks for the feedback, all. I've changed styling to match Milan's suggestions, which seem reasonable to me. I've left in the Implemented section. I suspect if we write tools that parse the specs or something, it would be useful to have them all follow a consistent structure.

**Comment by jvdp1** [comment]
I will merge this PR since most of us approved it.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
